---
#------------------------------------------------------------------
# This playbook uses vault to save secret and it also uses lineinfile which is used to search a text or put a text in file 
#
#    
#------------------------------------------------------------------
#
# Change History              
# Date        Name               Version    Description
# 2020/03/03  Siddhartha Singh   00.00      Started new code
# 
#
########################################################################
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Input the secret in ini file
      lineinfile:
        path: sec.ini
        line: " SECRET_KEY: {{mypass}}"
      no_log: True
...
